#!/usr/bin/env node
// Run once to generate pokemon-data.js from PokeAPI.
// Usage: node scripts/generate-data.js
// Takes ~2-3 minutes for 649 requests.

const https = require('https');
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'pokemon-data.js');
const TOTAL = 649;
const DELAY_MS = 150;

// Special display names that can't be derived from the slug
const NAME_OVERRIDES = {
  'nidoran-f':      'Nidoran\u2640',
  'nidoran-m':      'Nidoran\u2642',
  'mr-mime':        'Mr. Mime',
  'farfetchd':      "Farfetch\u2019d",
  'ho-oh':          'Ho-Oh',
  'mime-jr':        'Mime Jr.',
  'porygon-z':      'Porygon-Z',
  'wormadam-plant': 'Wormadam',  // base form only
};

const STAT_MAP = {
  'hp':              'hp',
  'attack':          'atk',
  'defense':         'def',
  'special-attack':  'spa',
  'special-defense': 'spd',
  'speed':           'spe',
};

function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(new Error('Bad JSON from ' + url + ': ' + data.slice(0, 80))); }
      });
    });
    req.on('error', reject);
    req.setTimeout(10000, () => { req.destroy(); reject(new Error('Timeout: ' + url)); });
  });
}

function delay(ms) {
  return new Promise(r => setTimeout(r, ms));
}

function slugToName(slug) {
  if (NAME_OVERRIDES[slug]) return NAME_OVERRIDES[slug];
  return slug
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// Returns the Gen 5 base stat value, falling back to current if no past_values entry.
function getGen5Stat(pokemon, apiStatName) {
  // past_values contains stats that were DIFFERENT in an older generation.
  // Each entry: { generation: { name: "generation-v" }, stats: [{ base_stat, stat: { name } }] }
  // If a stat changed after Gen 5, its Gen 5 value appears in a past_values entry
  // for the last generation it was valid (generation-v or earlier).
  if (Array.isArray(pokemon.past_values)) {
    for (const pv of pokemon.past_values) {
      if (pv.generation && pv.generation.name === 'generation-v') {
        const s = pv.stats.find(st => st.stat.name === apiStatName);
        if (s) return s.base_stat;
      }
    }
  }
  // Also check past_stats field name used by some API versions
  if (Array.isArray(pokemon.past_stats)) {
    for (const pv of pokemon.past_stats) {
      if (pv.generation && pv.generation.name === 'generation-v') {
        const s = pv.stats.find(st => st.stat.name === apiStatName);
        if (s) return s.base_stat;
      }
    }
  }
  // No Gen 5-specific override — current stat IS the Gen 5 stat
  const cur = pokemon.stats.find(s => s.stat.name === apiStatName);
  return cur ? cur.base_stat : 0;
}

async function main() {
  console.log(`Fetching ${TOTAL} Pokémon from PokeAPI…\n`);
  const entries = [];
  let failed = 0;

  for (let id = 1; id <= TOTAL; id++) {
    const url = `https://pokeapi.co/api/v2/pokemon/${id}`;
    try {
      const data = await fetchJSON(url);
      const slug = data.name; // e.g. "bulbasaur", "nidoran-f"
      const dex  = data.id;
      const name = slugToName(slug);

      const stats = {};
      for (const [apiName, ourKey] of Object.entries(STAT_MAP)) {
        stats[ourKey] = getGen5Stat(data, apiName);
      }

      entries.push({ slug, dex, name, ...stats });

      if (id % 50 === 0 || id === TOTAL) {
        process.stdout.write(`\r  ${id}/${TOTAL} done`);
      }
    } catch (e) {
      console.error(`\n  ERROR #${id}: ${e.message}`);
      failed++;
    }

    if (id < TOTAL) await delay(DELAY_MS);
  }

  console.log(`\n\nFetched ${entries.length} Pokémon (${failed} errors)\n`);

  // Sort by dex number (should already be in order, but be safe)
  entries.sort((a, b) => a.dex - b.dex);

  // Build JS output
  const lines = [
    '// Auto-generated by scripts/generate-data.js — do not edit by hand.',
    '// Gen 5 base stats for national dex #001\u2013649.',
    '// Regenerate: node scripts/generate-data.js',
    'var POKEMON = {',
  ];

  for (const e of entries) {
    const dexStr = String(e.dex).padStart(3, '0');
    lines.push(
      `  "${e.slug}": { name: "${e.name}", dex: ${e.dex}, ` +
      `hp: ${e.hp}, atk: ${e.atk}, def: ${e.def}, spa: ${e.spa}, spd: ${e.spd}, spe: ${e.spe} },`
    );
  }

  lines.push('};');
  lines.push('');

  fs.writeFileSync(OUT, lines.join('\n'), 'utf8');
  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  console.log(`Written: pokemon-data.js (${entries.length} entries, ${kb} KB)`);

  // Spot-check a known Gen-5-specific stat
  const alakazam = entries.find(e => e.slug === 'alakazam');
  if (alakazam) {
    const spd = alakazam.spd;
    const ok = spd === 85;
    console.log(`Spot-check Alakazam Sp.Def: ${spd} (expected 85 for Gen 5) ${ok ? '✓' : '✗ MISMATCH'}`);
  }
}

main().catch(e => { console.error('Fatal:', e); process.exit(1); });
